# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/akonadi-mime': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'pim/messagelib': '@same'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD']
  cppcheck-arguments: '--enable=warning,performance,portability,style --suppress-xml=cppcheck-suppressions.xml -DQTEST_AKONADIMAIN\(X\)= -DAKONADI_CALENDAR_DECL_DEPRECATED_TEXT\(X\)= -DKCONFIGGROUP_DECLARE_ENUM_QOBJECT\(X,Y\)='
  cppcheck-ignore-files:
    - autotests
  require-cppcheck-clean: True
