# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'pim/akonadi': '@same'
    'pim/akonadi-mime': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'pim/messagelib': '@same'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD']
  cppcheck-arguments:
    - --enable=warning,performance,portability,style
    - --suppress-xml=cppcheck-suppressions.xml
    - -DQTEST_AKONADIMAIN(X)=
    - -DAKONADI_CALENDAR_DECL_DEPRECATED_TEXT(X)=
    - -DKCONFIGGROUP_DECLARE_ENUM_QOBJECT(X,Y)=
  cppcheck-ignore-files:
    - autotests
  require-cppcheck-clean: True
